name: AFL
favicon: null
layout_spectrum: 1
typography_spectrum: 0.667060409905389
title: AFL News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1875
  lightness: 0.7078102615196258
  saturation: 0.5
  rhythmicContrast: 0.5095150691922754
purpose: []
